### ISSUE TITLE
chartEnabled=trueでfont.ttfが配置されていない場合は起動しないようにする

### ISSUE THREAD

**Issue by massongit** [syuilo/ai#110]
```
23:46:19 [AiOS]: [chart]: Chart rendering...
/ai/node_modules/canvas/index.js:48
  return Canvas._registerFont(fs.realpathSync(src), fontFace)
                ^

Error: Could not parse font file
    at Object.registerFont (/ai/node_modules/canvas/index.js:48:17)
    at Object.renderChart (/ai/built/modules/chart/render-chart.js:25:14)
    at default_1.genChart (/ai/built/modules/chart/index.js:119:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default_1.post (/ai/built/modules/chart/index.js:40:22)
```

`font.ttf` を配置せずに `chartEnabled: true` な状態で起動すると、チャート機能実行時に上記エラーで落ちます。
従って、そのような場合はbot起動前に上記の状態になっていないかをチェックし、なっている場合は起動しないようにすると良いかと思います。

**Comment by massongit** [comment]
https://github.com/syuilo/ai/blob/a3af63daa87f241b5e742b495eda12557c3d2e07/docker-compose.yml#L11
Dockerの場合は上記をlong syntaxで書けば解決しそうですね。
https://zenn.dev/sarisia/articles/0c1db052d09921
