### ISSUE TITLE
カスタム絵文字チェックに失敗する

### ISSUE THREAD

**Issue by noko1024** [syuilo/ai#135]
カスタム絵文字チェックで`admin/emoji/list`を叩くと403でレスポンスされてしまう

```
[AiOS]: [checkCustomEmojis]: Check CustomEmojis requested
[AiOS]: [checkCustomEmojis]: Start to Check CustomEmojis.
[AiOS]: [checkCustomEmojis]: CustomEmojis fetching...
[AiOS]: [checkCustomEmojis]: lastId is null
[AiOS]: API: admin/emoji/list
Uncaught exception: Response code 403 (Forbidden)
```

`admin/*`の読み書きできるトークンを発行できるのは、管理者アカウントだけで
一般ユーザーとして運用している藍ちゃんでは使えない?

間違ってたらごめんなさい

**Comment by tetsuya-ki** [comment]
ご指摘の通りです。
` read:admin:emoji`がないと「API: admin/emoji/list」実行時にエラーになります。
＊自分の使ってるサーバーがデフォルトでカスタム絵文字管理許可してて失念しておりました

バグを埋め込んでしまい申し訳ないです。修正のプルリクエストを作ろうと思います。
(try-catchして絵文字取得でエラーだったらログ出力&だめです的リアクションorだめですメッセージ)
```
misskey-app-1  | 14:34:11 [AiOS]: API: admin/emoji/list
misskey-app-1  | Uncaught exception: Response code 403 (Forbidden)
misskey-app-1  | HTTPError: Response code 403 (Forbidden)
misskey-app-1  |     at Request.<anonymous> (file:///ai/node_modules/got/dist/source/as-promise/index.js:86:42)
misskey-app-1  |     at Object.onceWrapper (node:events:633:26)
misskey-app-1  |     at Request.emit (node:events:530:35)
misskey-app-1  |     at Request._onResponseBase (file:///ai/node_modules/got/dist/source/core/index.js:603:22)
misskey-app-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
misskey-app-1  |     at async Request._onResponse (file:///ai/node_modules/got/dist/source/core/index.js:645:13) {
misskey-app-1  |   input: undefined,
...(省略)...
```
