### ISSUE TITLE
UnhandledPromiseRejectionWarning という警告?が表示される

### ISSUE THREAD

**Issue by tkmrgit** [syuilo/ai#38]
#10 関連?
```
(node:20440) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at default_1.learn (/root/ai/built/modules/keyword/index.js:54:29)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:20440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

devで藍ちゃんを動かしてみたものの、一応動きましたがこのエラーが表示されてしまいます。

**Comment by u1-liquid** [comment]
https://github.com/syuilo/ai/blob/9d05f9794295a6c11d0a9d816f0af10e1ad8d266/src/modules/keyword/index.ts#L53-L66
で`keywords`などが空の場合起こる？
