### ISSUE TITLE
起動エラー

### ISSUE THREAD

**Issue by YuzuRyo61** [syuilo/ai#68]
`npm start` したらエラーが発生する。

```
> @ start /home/misskey/aiMisskey
> node ./built

/home/misskey/aiMisskey/built/message.js:61
        if (!opts?.immediate) {
                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/misskey/aiMisskey/built/ai.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node ./built`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/misskey/.npm/_logs/2020-10-31T03_36_03_626Z-debug.log
```

**Comment by syuilo** [comment]
Node.jsのバージョンはなんですか？

**Comment by YuzuRyo61** [comment]
`v12.19.0`です

**Comment by syuilo** [comment]
v14系にアップデートすると直ります👌
