### ISSUE TITLE
公開範囲:フォローでtodoを登録すると催促時の引用RTでコケる

### ISSUE THREAD

**Issue by ThinaticSystem** [syuilo/ai#83]
公開範囲をフォロワー限定にして`@ai todo でぼび`リプライすると
引用RNができないため催促するタイミングでエラーが起こります

ログ
```
10月 20 16:17:03 debobiSv honi[2922664]: 16:17:03 [AiOS]: Ai am now running!
10月 20 16:17:03 debobiSv honi[2922664]: /home/honi/honi/node_modules/request-promise-core/lib/errors.js:32
10月 20 16:17:03 debobiSv honi[2922664]:         Error.captureStackTrace(this);
10月 20 16:17:03 debobiSv honi[2922664]:               ^
10月 20 16:17:03 debobiSv honi[2922664]: <ref *9> StatusCodeError: 500 - {"error":{"message":"Internal error occurred. Please contact us if the error persists.","code":"INTERNAL_ERROR","id":"5d37dbcb-891e-41ca-a3d6-e690c97775ac","kind":"server","info":{"e":{}}}}
10月 20 16:17:03 debobiSv honi[2922664]:     at new StatusCodeError (/home/honi/honi/node_modules/request-promise-core/lib/errors.js:32:15)
10月 20 16:17:03 debobiSv honi[2922664]:     at Request.plumbing.callback (/home/honi/honi/node_modules/request-promise-core/lib/plumbing.js:104:33)
10月 20 16:17:03 debobiSv honi[2922664]:     at Request.RP$callback [as _callback] (/home/honi/honi/node_modules/request-promise-core/lib/plumbing.js:46:31)
10月 20 16:17:03 debobiSv honi[2922664]:     at Request.self.callback (/home/honi/honi/node_modules/request/request.js:185:22)
10月 20 16:17:03 debobiSv honi[2922664]:     at Request.emit (node:events:394:28)
10月 20 16:17:03 debobiSv honi[2922664]:     at Request.<anonymous> (/home/honi/honi/node_modules/request/request.js:1154:10)
10月 20 16:17:03 debobiSv honi[2922664]:     at Request.emit (node:events:394:28)
10月 20 16:17:03 debobiSv honi[2922664]:     at IncomingMessage.<anonymous> (/home/honi/honi/node_modules/request/request.js:1076:12)
10月 20 16:17:03 debobiSv honi[2922664]:     at Object.onceWrapper (node:events:513:28)
10月 20 16:17:03 debobiSv honi[2922664]:     at IncomingMessage.emit (node:events:406:35) {
10月 20 16:17:03 debobiSv honi[2922664]:   statusCode: 500,
10月 20 16:17:03 debobiSv honi[2922664]:   error: {
10月 20 16:17:03 debobiSv honi[2922664]:     error: {
10月 20 16:17:03 debobiSv honi[2922664]:       message: 'Internal error occurred. Please contact us if the error persists.',
10月 20 16:17:03 debobiSv honi[2922664]:       code: 'INTERNAL_ERROR',
10月 20 16:17:03 debobiSv honi[2922664]:       id: '5d37dbcb-891e-41ca-a3d6-e690c97775ac',
10月 20 16:17:03 debobiSv honi[2922664]:       kind: 'server',
10月 20 16:17:03 debobiSv honi[2922664]:       info: { e: {} }
10月 20 16:17:03 debobiSv honi[2922664]:     }
10月 20 16:17:03 debobiSv honi[2922664]:   },
10月 20 16:17:03 debobiSv honi[2922664]:   options: {
10月 20 16:17:03 debobiSv honi[2922664]:     json: {
10月 20 16:17:03 debobiSv honi[2922664]:       i: '(トークン)',
10月 20 16:17:03 debobiSv honi[2922664]:       renoteId: '8s1ccg7bqd',
10月 20 16:17:03 debobiSv honi[2922664]:       text: '@honiBEKO13 これやった？'
10月 20 16:17:03 debobiSv honi[2922664]:     },
10月 20 16:17:03 debobiSv honi[2922664]:     uri: 'https://honi.club/api/notes/create',
10月 20 16:17:03 debobiSv honi[2922664]:     method: 'POST',
10月 20 16:17:03 debobiSv honi[2922664]:     callback: [Function: RP$callback],
10月 20 16:17:03 debobiSv honi[2922664]:     transform: undefined,
10月 20 16:17:03 debobiSv honi[2922664]:     simple: true,
10月 20 16:17:03 debobiSv honi[2922664]:     resolveWithFullResponse: false,
10月 20 16:17:03 debobiSv honi[2922664]:     transform2xxOnly: false
10月 20 16:17:03 debobiSv honi[2922664]:   },
︙
```

**Comment by syuilo** [comment]
fixed
